#!/usr/bin/env python3
"""Regenerate schema_v2.sql from the authoritative database.

The schema file is what `install.py` runs on a fresh machine. When tables,
views or indexes are added directly to `aimi.db` and the file is not updated,
a fresh install silently produces a database that the CLI cannot query. This
script makes the file a faithful projection of the live database, and
`validate_catalogue.py` fails when the two drift apart again.

Usage:
    python dump_schema.py            # rewrite schema_v2.sql
    python dump_schema.py --check    # exit 1 if the file is out of date
"""
from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DB = ROOT / "aimi.db"
SCHEMA = ROOT / "schema_v2.sql"
SCHEMA_VERSION = 2

HEADER = """-- AIMI schema
--
-- Generated by dump_schema.py from the authoritative database.
-- Do not hand-edit: apply the change to the database, then regenerate.
-- `validate_catalogue.py` fails when this file and the database disagree.

PRAGMA foreign_keys=ON;
BEGIN;
"""

FOOTER = f"""
PRAGMA user_version={SCHEMA_VERSION};
COMMIT;
"""


def idempotent(sql: str, kind: str) -> str:
    """Add IF NOT EXISTS so the schema can be applied to a partial database."""
    prefix = {
        "table": "CREATE TABLE ",
        "index": "CREATE INDEX ",
        "view": "CREATE VIEW ",
        "trigger": "CREATE TRIGGER ",
    }[kind]
    unique = "CREATE UNIQUE INDEX "
    for start in (unique, prefix):
        if sql.startswith(start) and "IF NOT EXISTS" not in sql[: len(start) + 20]:
            return start + "IF NOT EXISTS " + sql[len(start) :]
    return sql


def build(connection: sqlite3.Connection) -> str:
    sections: list[str] = [HEADER]
    # sqlite_master rowid order preserves creation order, which keeps
    # view-on-view and trigger-on-table dependencies valid on replay.
    for kind in ("table", "index", "view", "trigger"):
        rows = connection.execute(
            "SELECT name, sql FROM sqlite_master "
            "WHERE type=? AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL "
            "ORDER BY rowid",
            (kind,),
        ).fetchall()
        if not rows:
            continue
        sections.append(f"\n-- {kind}s ({len(rows)})\n")
        for name, sql in rows:
            statement = idempotent(sql.strip(), kind)
            sections.append(f"{statement};\n")
    sections.append(FOOTER)
    return "".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate schema_v2.sql from aimi.db")
    parser.add_argument("--check", action="store_true", help="Report drift without writing")
    args = parser.parse_args()

    if not DB.exists():
        print(f"No database at {DB}", file=sys.stderr)
        return 1

    connection = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    try:
        generated = build(connection)
    finally:
        connection.close()

    current = SCHEMA.read_text(encoding="utf-8") if SCHEMA.exists() else ""
    if generated == current:
        print(f"schema_v2.sql is up to date ({SCHEMA.stat().st_size} bytes)")
        return 0
    if args.check:
        print("schema_v2.sql is out of date; run: python dump_schema.py", file=sys.stderr)
        return 1
    SCHEMA.write_text(generated, encoding="utf-8")
    print(f"Rewrote {SCHEMA} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
